- hosts: localhost
  become: true
  tasks:
# AMI build
  - name: Basic AMI Creation
    amazon.aws.ec2_ami:
      instance_id: i-097f64d75a423772d
      wait: true
      region: ap-south-1
      name: "webapp"
      tags:
        Name: Node_01_AMI
        Service: TestService
    
