---
- hosts: localhost
  become: true
  tasks:
    - name: create launch config
      community.aws.autoscaling_launch_config:
        name: my_new_lc
        image_id: ami-04c736683313f2123
        key_name: ansible_jenkins
        region: ap-south-1
        security_groups: sg-0e8deef22f4f4dfdb
        instance_type: t2.micro
        assign_public_ip: true
    - amazon.aws.autoscaling_group:
        name: myasg
        launch_config_name: my_new_lc
        health_check_period: 60
        replace_all_instances: true
        min_size: 2
        max_size: 3
        desired_capacity: 2
        region: ap-south-1
        availability_zones:
          - ap-south-1a
          - ap-south-1b
        vpc_zone_identifier:
          - subnet-0357320ad1fc374df
          - subnet-06c405bc87dde0e37
